apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metric-pusher
spec:
  rules:
  - host: pusher.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: metric-pusher
            port:
              number: 8082
