apiVersion: apps/v1
kind: Deployment
metadata:
  name: metric-pusher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: metric-pusher
  template:
    metadata:
      labels:
        app: metric-pusher
    spec:
      containers:
      - name: metric-pusher
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8082
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
